project_type: ruby
test:
  rubocop:
    command: /home/hien/.rbenv/shims/bundle exec rubocop --require rubocop/formatter/checkstyle_formatter --format RuboCop::Formatter::CheckstyleFormatter --no-color --out .framgia-ci-reports/rubocop.xml app/ lib/
  rspec:
    command: /home/hien/.rbenv/shims/bundle exec rspec --format html --out .framgia-ci-reports/rspec.html spec/
